In [25]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import confusion_matrix,classification_report,mean_absolute_error
import seaborn as sns
import numpy as np

In [26]:
df=pd.read_csv('/Users/_senyonjo/Downloads/teams.csv')
df.drop(columns=['Unnamed: 0'],inplace=True)

In [27]:
df

,team,country,year,events,athletes,age,height,weight,medals,prev_medals,prev_3_medals
0,AFG,Afghanistan,1964,8,8,22.0,161.0,64.2,0,0.0,0.0
1,AFG,Afghanistan,1968,5,5,23.2,170.2,70.0,0,0.0,0.0
2,AFG,Afghanistan,1972,8,8,29.0,168.3,63.8,0,0.0,0.0
3,AFG,Afghanistan,1980,11,11,23.6,168.4,63.2,0,0.0,0.0
4,AFG,Afghanistan,2004,5,5,18.6,170.8,64.8,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
2139,ZIM,Zimbabwe,2000,19,26,25.0,179.0,71.1,0,0.0,0.0
2140,ZIM,Zimbabwe,2004,11,14,25.1,177.8,70.5,3,0.0,0.0
2141,ZIM,Zimbabwe,2008,15,16,26.1,171.9,63.7,4,3.0,1.0
2142,ZIM,Zimbabwe,2012,8,9,27.3,174.4,65.2,0,4.0,2.3
2143,ZIM,Zimbabwe,2016,13,31,27.5,167.8,62.2,0,0.0,2.3

In [28]:
df.isna().any(axis=0)

team             False
country          False
year             False
events           False
athletes         False
age              False
height           False
weight           False
medals           False
prev_medals       True
prev_3_medals     True
dtype: bool

In [29]:
df.dropna(inplace=True)

In [30]:
df.isna().any(axis=0)

team             False
country          False
year             False
events           False
athletes         False
age              False
height           False
weight           False
medals           False
prev_medals      False
prev_3_medals    False
dtype: bool

In [31]:
#splitting the data for the predictions 
trainset=df[df['year']<2012].copy()
testset=df[df['year']>=2012].copy()

In [32]:
#we define our predictors and the traget
target=['medals']
predictors=['events','athletes','prev_medals']

#we create a insstance of the model
model=LinearRegression()

#we fir the model
model.fit(trainset[predictors],trainset[target])

LinearRegression()

In [33]:
#predicting the testset
model.predict(testset[predictors])

array([[ 4.14631164e-01],
       [ 9.06609940e-01],
       [-5.27318313e-01],
       [-2.67293075e-01],
       [-3.55746506e-01],
       [-4.42279726e-01],
       [-2.67293075e-01],
       [ 6.06927759e-02],
       [ 4.87557366e+00],
       [ 2.78799182e+00],
       [ 6.06927759e-02],
       [ 8.24514001e-01],
       [ 4.36914577e+01],
       [ 3.58107287e+01],
       [ 1.20375686e-01],
       [-2.02142934e+00],
       [ 6.06927759e-02],
       [-3.53395373e-02],
       [ 6.06927759e-02],
       [ 6.06927759e-02],
       [ 1.39190630e+02],
       [ 1.21794346e+02],
       [-3.68205037e+00],
       [-3.72001907e+00],
       [-3.39355552e+00],
       [-1.00797975e+00],
       [ 5.88164333e+00],
       [ 4.33966660e+00],
       [-4.31286000e-01],
       [-4.31286000e-01],
       [ 1.96614000e-01],
       [-6.23350627e-01],
       [-2.67293075e-01],
       [-5.27318313e-01],
       [ 8.95148913e+00],
       [ 5.47198712e+00],
       [-1.03300149e-01],
       [-2.67293075e-01],
       [-1.99332463e-01],
       [-5.95278926e-01],
       [ 3.88678627e-01],
       [ 3.88678627e-01],
       [-5.95278926e-01],
       [ 1.00581687e-01],
       [ 2.24685701e-01],
       [ 2.24685701e-01],
       [ 1.98497609e+01],
       [ 1.52869285e+01],
       [-1.03300149e-01],
       [-4.59357701e-01],
       [ 6.06927759e-02],
       [ 1.87431300e+00],
       [ 7.02439257e+01],
       [ 8.82789922e+01],
       [-3.91397089e-01],
       [ 1.13412620e+00],
       [ 2.24685701e-01],
       [ 2.24685701e-01],
       [-6.50200937e-01],
       [-4.65945148e+00],
       [-1.03300149e-01],
       [-1.03300149e-01],
       [-2.67293075e-01],
       [-2.67293075e-01],
       [-2.67293075e-01],
       [-2.67293075e-01],
       [ 3.58211483e+01],
       [ 6.28730493e+01],
       [ 3.60606926e-01],
       [-1.03300149e-01],
       [-3.53395373e-02],
       [-5.27318313e-01],
       [ 3.88678627e-01],
       [ 3.88678627e-01],
       [-2.64952830e+00],
       [-2.63559192e+00],
       [ 1.55731498e+02],
       [ 1.18949199e+02],
       [-9.23264776e-01],
       [-5.55390015e-01],
       [ 2.48595851e+00],
       [ 6.72338285e-01],
       [ 6.06927759e-02],
       [ 6.06927759e-02],
       [-7.59271851e-01],
       [-7.59271851e-01],
       [-2.15672604e+00],
       [ 8.93331443e+00],
       [ 2.24685701e-01],
       [ 6.06927759e-02],
       [ 2.24685701e-01],
       [-1.03300149e-01],
       [-1.08725770e+00],
       [-8.55304164e-01],
       [ 1.05116406e+01],
       [ 2.75462081e+01],
       [ 2.60862253e+01],
       [ 4.23425986e+00],
       [-1.01929709e+00],
       [-1.25336979e+00],
       [ 3.17204679e+00],
       [ 5.15025680e+00],
       [ 2.09139962e+01],
       [ 1.82683951e+01],
       [ 6.06927759e-02],
       [-1.99332463e-01],
       [ 3.88678627e-01],
       [ 3.88678627e-01],
       [ 2.11596458e+00],
       [ 3.28296897e-01],
       [-3.71326367e+00],
       [-1.48764145e+00],
       [-2.43088660e+00],
       [-5.89194676e-01],
       [ 7.28481687e-01],
       [ 1.12442815e+00],
       [-1.08725770e+00],
       [-9.23264776e-01],
       [ 7.36308379e+01],
       [ 7.00688421e+01],
       [-7.65629343e-01],
       [ 1.17189594e+00],
       [ 7.83330394e+00],
       [ 7.96922517e+00],
       [-7.59271851e-01],
       [ 7.46695149e+00],
       [-4.02165448e+00],
       [-2.10988277e+00],
       [ 7.75991028e+01],
       [ 9.54134778e+01],
       [-2.67293075e-01],
       [-1.03300149e-01],
       [ 2.81606353e+00],
       [ 4.14631164e-01],
       [ 3.88678627e-01],
       [ 1.16018078e+02],
       [ 1.19115510e+02],
       [ 6.06927759e-02],
       [-1.03300149e-01],
       [-6.99588941e-01],
       [ 9.01848207e-02],
       [ 3.88678627e-01],
       [ 5.52671552e-01],
       [ 1.02186872e+02],
       [ 1.03224257e+02],
       [-4.31286000e-01],
       [-5.55390015e-01],
       [ 2.07285978e+00],
       [ 1.14908501e+00],
       [-5.95278926e-01],
       [ 1.20652409e+00],
       [-2.03132634e+00],
       [-3.25555641e-01],
       [ 6.06927759e-02],
       [-1.03300149e-01],
       [-5.95278926e-01],
       [-1.03300149e-01],
       [-2.67293075e-01],
       [-4.31286000e-01],
       [-1.03300149e-01],
       [-9.23264776e-01],
       [-3.94753533e+00],
       [-3.69881833e-01],
       [ 2.55603829e+00],
       [ 2.88402414e+00],
       [ 2.18012226e+01],
       [ 2.10232660e+01],
       [ 4.25796857e+00],
       [ 1.35214336e+00],
       [ 3.02096780e+00],
       [ 8.43375677e+00],
       [ 6.06927759e-02],
       [ 4.28567538e-01],
       [-4.89140501e+00],
       [ 6.22710506e+00],
       [-9.90202951e-01],
       [ 3.12901628e+00],
       [-5.95278926e-01],
       [ 3.37600291e+00],
       [ 1.06950019e+01],
       [-1.57923648e+00],
       [-1.84581816e+00],
       [-3.41566764e+00],
       [ 3.26210748e-02],
       [-4.31286000e-01],
       [ 5.10487816e+01],
       [ 7.19301290e+01],
       [ 3.88678627e-01],
       [ 6.06927759e-02],
       [ 1.47460616e+01],
       [ 2.29549060e+01],
       [-7.59271851e-01],
       [-5.95278926e-01],
       [ 5.75657917e+01],
       [ 8.54840008e+01],
       [-1.77077853e+00],
       [-6.90788669e-01],
       [ 1.36683898e+01],
       [ 1.52916667e+01],
       [-3.79380926e-01],
       [-1.60730818e+00],
       [ 2.24685701e-01],
       [ 2.24685701e-01],
       [ 7.08437540e+01],
       [ 5.69920872e+01],
       [ 5.08345360e-01],
       [ 2.03638572e+00],
       [-8.55304164e-01],
       [ 2.24685701e-01],
       [-1.03300149e-01],
       [-6.85851521e-01],
       [ 5.18242359e-01],
       [ 6.06927759e-02],
       [-4.31286000e-01],
       [ 2.24685701e-01],
       [ 6.06927759e-02],
       [ 2.92646313e-01],
       [ 6.06927759e-02],
       [-3.63325388e-01],
       [-9.23264776e-01],
       [-7.59271851e-01],
       [ 6.06927759e-02],
       [ 2.24685701e-01],
       [-5.54168624e-01],
       [ 3.28119199e+00],
       [-1.08725770e+00],
       [-1.34728294e+00],
       [-4.31286000e-01],
       [-2.67293075e-01],
       [ 1.78354145e+00],
       [-1.98173939e+00],
       [ 3.14161570e-01],
       [ 3.40114107e-01],
       [ 2.24685701e-01],
       [-1.03300149e-01],
       [-1.48532333e+00],
       [-1.29537787e+00],
       [-1.03300149e-01],
       [ 6.06927759e-02],
       [ 1.35084768e+00],
       [ 1.76486709e+01],
       [-1.80341218e+00],
       [-1.43765658e+00],
       [ 6.06927759e-02],
       [-1.03300149e-01],
       [ 6.06927759e-02],
       [-2.67293075e-01],
       [-2.67293075e-01],
       [-2.67293075e-01],
       [-1.03300149e-01],
       [-5.95278926e-01],
       [ 5.03956659e+00],
       [ 1.48184595e+01],
       [-2.67293075e-01],
       [-5.95278926e-01],
       [-2.67293075e-01],
       [-1.99332463e-01],
       [-9.38700018e-03],
       [-1.08725770e+00],
       [ 3.88678627e-01],
       [ 3.88678627e-01],
       [-2.67293075e-01],
       [-5.95278926e-01],
       [-3.63325388e-01],
       [-2.95364776e-01],
       [-2.67293075e-01],
       [-1.03300149e-01],
       [ 5.61928144e+01],
       [ 7.57766823e+01],
       [-1.03300149e-01],
       [-4.31286000e-01],
       [ 1.75798868e+01],
       [ 4.32301420e+00],
       [-2.67293075e-01],
       [-2.67293075e-01],
       [ 1.35102545e+01],
       [ 9.18463639e+00],
       [ 3.88678627e-01],
       [ 3.88678627e-01],
       [ 2.38167074e+01],
       [ 3.33471933e+01],
       [ 2.24685701e-01],
       [ 6.06927759e-02],
       [ 3.21200999e+00],
       [-4.31286000e-01],
       [ 8.66453130e-02],
       [-1.57923648e+00],
       [-9.23264776e-01],
       [-1.08725770e+00],
       [-1.11532940e+00],
       [-2.48341621e+00],
       [-1.08725770e+00],
       [-1.41524355e+00],
       [-1.03300149e-01],
       [-2.67293075e-01],
       [-1.03300149e-01],
       [-2.67293075e-01],
       [-5.95278926e-01],
       [-5.95278926e-01],
       [ 1.51351783e+01],
       [ 1.89180370e+01],
       [-4.88402509e+00],
       [ 2.51485370e+00],
       [ 7.33900705e+00],
       [ 2.53594337e+00],
       [-2.68729804e+00],
       [ 9.00053495e-01],
       [-1.18329001e+00],
       [ 3.90363227e+00],
       [ 2.19758113e+01],
       [ 1.51451496e+01],
       [ 9.29533157e+00],
       [ 1.50905285e+01],
       [ 1.30657140e+02],
       [ 1.18692884e+02],
       [-4.31286000e-01],
       [-4.31286000e-01],
       [-7.59271851e-01],
       [-7.59271851e-01],
       [ 1.80403427e+00],
       [ 1.46423121e+00],
       [-2.67293075e-01],
       [-9.23264776e-01],
       [-3.69682880e-01],
       [ 1.36415952e+00],
       [ 1.15249985e+00],
       [ 1.22046046e+00],
       [ 3.88678627e-01],
       [ 6.06927759e-02],
       [-4.70569788e+00],
       [ 2.54544247e+00],
       [ 6.06927759e-02],
       [ 4.56639239e-01],
       [ 6.06927759e-02],
       [ 2.24685701e-01],
       [ 2.02502466e+01],
       [ 1.89125496e+01],
       [-5.95278926e-01],
       [-9.23264776e-01],
       [ 3.88678627e-01],
       [ 2.24685701e-01],
       [ 8.10577627e-01],
       [-2.67293075e-01],
       [ 9.33177797e+00],
       [ 7.02558210e+00],
       [-1.03300149e-01],
       [-2.67293075e-01],
       [ 2.02367073e+00],
       [-6.62018147e-01],
       [ 1.23866650e+01],
       [ 2.75825851e+01],
       [ 2.24685701e-01],
       [ 3.88678627e-01],
       [-9.23264776e-01],
       [-4.31286000e-01],
       [ 1.28653388e-01],
       [ 3.60606926e-01],
       [ 2.24685701e-01],
       [-4.31286000e-01],
       [-1.23165558e+00],
       [-1.60184846e+00],
       [-5.43373851e-01],
       [ 2.50638238e-01],
       [-9.23264776e-01],
       [-7.59271851e-01],
       [ 3.88678627e-01],
       [ 2.24685701e-01],
       [ 4.14631164e-01],
       [-1.03300149e-01],
       [ 3.63947480e-01],
       [-5.92137324e-01],
       [ 4.91162215e+00],
       [ 8.00719387e+00],
       [ 1.78122334e+00],
       [-7.70066624e-01],
       [ 1.41688808e+00],
       [-3.11453210e+00],
       [ 2.24685701e-01],
       [ 5.52671552e-01],
       [ 3.18393829e+00],
       [-8.55304164e-01],
       [-3.23436477e-01],
       [ 1.19026960e+00],
       [ 2.34755067e+01],
       [ 2.53136592e+01],
       [ 2.62399890e+00],
       [-8.83375865e-01],
       [ 2.79695752e+02],
       [ 2.39601586e+02],
       [-2.79160806e+00],
       [-6.00158574e+00],
       [-1.03300149e-01],
       [ 6.06927759e-02],
       [-6.60161300e+00],
       [-4.73416749e+00],
       [-2.14129503e+00],
       [-2.29135158e+00],
       [ 2.24685701e-01],
       [ 6.06927759e-02],
       [ 6.06927759e-02],
       [ 2.24685701e-01],
       [-4.31286000e-01],
       [-4.31286000e-01],
       [ 2.36437157e+00],
       [ 2.75992012e+00]])

In [34]:
testset['predictions']=model.predict(testset[predictors])

In [35]:
testset

,team,country,year,events,athletes,age,height,weight,medals,prev_medals,prev_3_medals,predictions
6,AFG,Afghanistan,2012,6,6,24.8,171.7,60.8,1,1.0,0.3,0.414631
7,AFG,Afghanistan,2016,3,3,24.7,173.7,74.0,0,1.0,0.7,0.906610
24,ALB,Albania,2012,9,10,25.7,176.8,80.2,0,0.0,0.0,-0.527318
25,ALB,Albania,2016,6,6,23.7,176.2,67.2,0,0.0,0.0,-0.267293
37,ALG,Algeria,2012,29,39,24.8,174.3,66.9,1,2.0,2.3,-0.355747
...,...,...,...,...,...,...,...,...,...,...,...,...
2111,YEM,Yemen,2016,3,3,19.3,169.7,65.7,0,0.0,0.0,0.224686
2131,ZAM,Zambia,2012,7,7,22.6,176.2,74.2,0,0.0,0.0,-0.431286
2132,ZAM,Zambia,2016,7,7,24.1,175.2,67.5,0,0.0,0.0,-0.431286
2142,ZIM,Zimbabwe,2012,8,9,27.3,174.4,65.2,0,4.0,2.3,2.364372
2143,ZIM,Zimbabwe,2016,13,31,27.5,167.8,62.2,0,0.0,2.3,2.759920

In [36]:
testset.loc[testset['predictions']<0,'predictions']=0

In [37]:
testset['predictions']=testset['predictions'].round()

In [38]:
testset

,team,country,year,events,athletes,age,height,weight,medals,prev_medals,prev_3_medals,predictions
6,AFG,Afghanistan,2012,6,6,24.8,171.7,60.8,1,1.0,0.3,0.0
7,AFG,Afghanistan,2016,3,3,24.7,173.7,74.0,0,1.0,0.7,1.0
24,ALB,Albania,2012,9,10,25.7,176.8,80.2,0,0.0,0.0,0.0
25,ALB,Albania,2016,6,6,23.7,176.2,67.2,0,0.0,0.0,0.0
37,ALG,Algeria,2012,29,39,24.8,174.3,66.9,1,2.0,2.3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2111,YEM,Yemen,2016,3,3,19.3,169.7,65.7,0,0.0,0.0,0.0
2131,ZAM,Zambia,2012,7,7,22.6,176.2,74.2,0,0.0,0.0,0.0
2132,ZAM,Zambia,2016,7,7,24.1,175.2,67.5,0,0.0,0.0,0.0
2142,ZIM,Zimbabwe,2012,8,9,27.3,174.4,65.2,0,4.0,2.3,2.0
2143,ZIM,Zimbabwe,2016,13,31,27.5,167.8,62.2,0,0.0,2.3,3.0

In [39]:
#checking the meanaberr
meanaberr=mean_absolute_error(testset['medals'],testset['predictions'])

In [40]:
meanaberr

3.269135802469136

In [41]:
absoluteerror=(testset['medals']-testset['predictions']).abs()
absoluteerror

6       1.0
7       1.0
24      0.0
25      0.0
37      1.0
       ...
2111    0.0
2131    0.0
2132    0.0
2142    2.0
2143    3.0
Length: 405, dtype: float64

In [42]:
errorperteam=absoluteerror.groupby(testset['team']).mean()
errorperteam

team
AFG    1.0
ALB    0.0
ALG    1.5
AND    0.0
ANG    4.0
      ...
VIE    1.0
VIN    0.0
YEM    0.0
ZAM    0.0
ZIM    2.5
Length: 204, dtype: float64

In [43]:
medalperteam=testset['medals'].groupby(testset['team']).mean()
medalperteam

team
AFG    0.5
ALB    0.0
ALG    1.5
AND    0.0
ANG    0.0
      ...
VIE    1.0
VIN    0.0
YEM    0.0
ZAM    0.0
ZIM    0.0
Name: medals, Length: 204, dtype: float64

In [44]:
erroratio=errorperteam/medalperteam
erroratio

team
AFG    2.0
ALB    NaN
ALG    1.0
AND    NaN
ANG    inf
      ...
VIE    1.0
VIN    NaN
YEM    NaN
ZAM    NaN
ZIM    inf
Length: 204, dtype: float64

In [46]:
erroratio=erroratio[~pd.isnull(erroratio)]
erroratio

team
AFG    2.000000
ALG    1.000000
ANG         inf
ANT         inf
ARG    0.951220
         ...
USA    0.109375
UZB    1.000000
VEN    1.000000
VIE    1.000000
ZIM         inf
Length: 112, dtype: float64

In [49]:
erroratio=erroratio[np.isfinite(erroratio)]
erroratio.sort_values()

team
FRA    0.028090
RUS    0.050980
ETH    0.066667
NZL    0.095238
HUN    0.104167
         ...
UGA    2.000000
GAB    2.000000
AFG    2.000000
BOT    3.000000
UAE    4.000000
Length: 97, dtype: float64

In [50]:
testset.loc[testset['team']=='FRA']

,team,country,year,events,athletes,age,height,weight,medals,prev_medals,prev_3_medals,predictions
679,FRA,France,2012,188,426,26.6,177.4,70.8,82,77.0,65.3,78.0
680,FRA,France,2016,202,512,27.1,177.9,72.4,96,82.0,70.7,95.0

In [ ]:
from sklearn.metrics import classification_report

print(classification_report())